config/routes.rb
Vinebox::Application.routes.draw do
  resources :boxes


  resources :vines do
    #post 'proxy', :on => :collection
  end
  
  match '/p/:vineid' => 'vines#proxy', :as => 'proxy'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :background, :bigad, :description, :query, :smallad, :title
  
  #belongs_to  :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  #has_many  :boxes
  
end

app/models/vine.rb
require 'nokogiri'
require 'open-uri'

class Vine < ActiveRecord::Base
  attr_accessible :uri, :vineid
  
  
  def self.proxy(vineid)
    @vineuri = "https://vine.co/v/" + vineid
    
    # scrape this vine's page and get the video uri
    @vinevideo = Nokogiri::HTML(open(@vineuri))
    @vinevideo = @vinevideo.at('meta[@property="twitter:player:stream"]')[:content]
    
    if @vinevideo.match(/mp4/i)
      # vinevideo has video, so return it
      @vinevideo
    else
      # vinevideo doesn't have video, so show default cat video
      "https://vines.s3.amazonaws.com/videos/2013/04/06/B15F7BDE-74A4-4D43-B81A-8E2AF2A5B1AC-305-000000935BA4A4CB_1.0.7.mp4?versionId=bCRp4zWMDa_VqxSl3ykWa0c5oERUxRih"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/controllers/vines_controller.rb
class VinesController < ApplicationController
  
  
  def proxy
    #default to video of Judd dancing
    @vinevideo = "https://vines.s3.amazonaws.com/videos/2013/04/06/B15F7BDE-74A4-4D43-B81A-8E2AF2A5B1AC-305-000000935BA4A4CB_1.0.7.mp4?versionId=bCRp4zWMDa_VqxSl3ykWa0c5oERUxRih"
    
    if params[:vineid]
      @vinevideo = Vine.proxy(params[:vineid])
    end
    
    #logger.debug params[:vinedata]
    render :json => params[:vinedata]
  end
  
  # GET /vines
  # GET /vines.json
  def index
    @vines = Vine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vines }
    end
  end

  # GET /vines/1
  # GET /vines/1.json
  def show
    @vine = Vine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vine }
    end
  end

  # GET /vines/new
  # GET /vines/new.json
  def new
    @vine = Vine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vine }
    end
  end

  # GET /vines/1/edit
  def edit
    @vine = Vine.find(params[:id])
  end

  # POST /vines
  # POST /vines.json
  def create
    @vine = Vine.new(params[:vine])

    respond_to do |format|
      if @vine.save
        format.html { redirect_to @vine, notice: 'Vine was successfully created.' }
        format.json { render json: @vine, status: :created, location: @vine }
      else
        format.html { render action: "new" }
        format.json { render json: @vine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vines/1
  # PUT /vines/1.json
  def update
    @vine = Vine.find(params[:id])

    respond_to do |format|
      if @vine.update_attributes(params[:vine])
        format.html { redirect_to @vine, notice: 'Vine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vines/1
  # DELETE /vines/1.json
  def destroy
    @vine = Vine.find(params[:id])
    @vine.destroy

    respond_to do |format|
      format.html { redirect_to vines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vines_helper.rb
module VinesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_field :query %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :background %><br />
    <%= f.text_field :background %>
  </div>
  <div class="field">
    <%= f.label :bigad %><br />
    <%= f.text_field :bigad %>
  </div>
  <div class="field">
    <%= f.label :smallad %><br />
    <%= f.text_field :smallad %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<h1>Listing boxes</h1>

<table>
  <tr>
    <th>Query</th>
    <th>Title</th>
    <th>Background</th>
    <th>Bigad</th>
    <th>Smallad</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boxes.each do |box| %>
  <tr>
    <td><%= box.query %></td>
    <td><%= box.title %></td>
    <td><%= box.background %></td>
    <td><%= box.bigad %></td>
    <td><%= box.smallad %></td>
    <td><%= box.description %></td>
    <td><%= link_to 'Show', box %></td>
    <td><%= link_to 'Edit', edit_box_path(box) %></td>
    <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Query:</b>
  <%= @box.query %>
</p>

<p>
  <b>Title:</b>
  <%= @box.title %>
</p>

<p>
  <b>Background:</b>
  <%= @box.background %>
</p>

<p>
  <b>Bigad:</b>
  <%= @box.bigad %>
</p>

<p>
  <b>Smallad:</b>
  <%= @box.smallad %>
</p>

<p>
  <b>Description:</b>
  <%= @box.description %>
</p>


<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

<br><br>

<%= content_tag :div, id: "player", data: {url: root_url+'p/'} do %>
	<a href="#" id="test_link">Click to Test</a>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Vinebox", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Vinebox" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Vinebox" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="/assets/app.css">
    <link rel="stylesheet" href="/assets/styles.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
	
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>

      <div class="header">
        <div id="header">
        	<a href="index.html" id="logo"><img src="assets/logo.png" /></a>
        	<a href="VineBox.html">Create a VineBox</a>
        </div>
      </div>
  
      
        <%= yield %>
      
	  
	  <div class="row">
	    <div class="twelve columns">
	    	<p id="footer"><a href="mailto:hello@vinebox.com?subject=Inquiry from VineBox">hello@vinebox.com</a><br />a product of curious entity</p>
	    </div>
	  </div>  
  
  
	</body>
	</html>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= collection_select :user, :role_ids, Role.all, :id, :name, checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/vines/_form.html.erb
<%= form_for(@vine) do |f| %>
  <% if @vine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vine.errors.count, "error") %> prohibited this vine from being saved:</h2>

      <ul>
      <% @vine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </div>
  <div class="field">
    <%= f.label :vineid %><br />
    <%= f.text_field :vineid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vines/edit.html.erb
<h1>Editing vine</h1>

<%= render 'form' %>

<%= link_to 'Show', @vine %> |
<%= link_to 'Back', vines_path %>

app/views/vines/index.html.erb
<h1>Listing vines</h1>

<table>
  <tr>
    <th>Uri</th>
    <th>Vineid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vines.each do |vine| %>
  <tr>
    <td><%= vine.uri %></td>
    <td><%= vine.vineid %></td>
    <td><%= link_to 'Show', vine %></td>
    <td><%= link_to 'Edit', edit_vine_path(vine) %></td>
    <td><%= link_to 'Destroy', vine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vine', new_vine_path %>

app/views/vines/new.html.erb
<h1>New vine</h1>

<%= render 'form' %>

<%= link_to 'Back', vines_path %>

app/views/vines/proxy.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uri:</b>
  <%= @vinevideo %>
</p>

app/views/vines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uri:</b>
  <%= @vine.uri %>
</p>

<p>
  <b>Vineid:</b>
  <%= @vine.vineid %>
</p>


<%= link_to 'Edit', edit_vine_path(@vine) %> |
<%= link_to 'Back', vines_path %>